find . -wholename './gt/ckb-200/47_Sarchia_Jihad/47_Sarchia_Jihad*.lstmf' > data/all-47_Sarchia_Jihad-ckb-200-lstmf
find . -wholename './gt/ckb-200/48_Sarchia_Jihan/48_Sarchia_Jihan*.lstmf' > data/all-48_Sarchia_Jihan-ckb-200-lstmf
find . -wholename './gt/ckb-200/49_Sarchia_Kani/49_Sarchia_Kani*.lstmf' > data/all-49_Sarchia_Kani-ckb-200-lstmf
find . -wholename './gt/ckb-200/50_Sarchia_Kalakin/50_Sarchia_Kalakin*.lstmf' > data/all-50_Sarchia_Kalakin-ckb-200-lstmf
find . -wholename './gt/ckb-200/51_Sarchia_Khalifan/51_Sarchia_Khalifan*.lstmf' > data/all-51_Sarchia_Khalifan-ckb-200-lstmf
find . -wholename './gt/ckb-200/52_Sarchia_Khursheed/52_Sarchia_Khursheed*.lstmf' > data/all-52_Sarchia_Khursheed-ckb-200-lstmf
find . -wholename './gt/ckb-200/53_Sarchia_Khwendnga/53_Sarchia_Khwendnga*.lstmf' > data/all-53_Sarchia_Khwendnga-ckb-200-lstmf
find . -wholename './gt/ckb-200/54_Sarchia_Kirkuk/54_Sarchia_Kirkuk*.lstmf' > data/all-54_Sarchia_Kirkuk-ckb-200-lstmf
find . -wholename './gt/ckb-200/55_Sarchia_Kurdish/55_Sarchia_Kurdish*.lstmf' > data/all-55_Sarchia_Kurdish-ckb-200-lstmf
find . -wholename './gt/ckb-200/57_Sarchia_Kurdistan/57_Sarchia_Kurdistan*.lstmf' > data/all-57_Sarchia_Kurdistan-ckb-200-lstmf
find . -wholename './gt/ckb-200/58_Sarchia_Lina/58_Sarchia_Lina*.lstmf' > data/all-58_Sarchia_Lina-ckb-200-lstmf
find . -wholename './gt/ckb-200/59_Sarchia_Lumia/59_Sarchia_Lumia*.lstmf' > data/all-59_Sarchia_Lumia-ckb-200-lstmf
find . -wholename './gt/ckb-200/60_Sarchia_Makka/60_Sarchia_Makka*.lstmf' > data/all-60_Sarchia_Makka-ckb-200-lstmf

find . -wholename './gt/ckb/47_Sarchia_Jihad/47_Sarchia_Jihad*.lstmf' > data/all-47_Sarchia_Jihad-ckb-lstmf
find . -wholename './gt/ckb/48_Sarchia_Jihan/48_Sarchia_Jihan*.lstmf' > data/all-48_Sarchia_Jihan-ckb-lstmf
find . -wholename './gt/ckb/49_Sarchia_Kani/49_Sarchia_Kani*.lstmf' > data/all-49_Sarchia_Kani-ckb-lstmf
find . -wholename './gt/ckb/50_Sarchia_Kalakin/50_Sarchia_Kalakin*.lstmf' > data/all-50_Sarchia_Kalakin-ckb-lstmf
find . -wholename './gt/ckb/51_Sarchia_Khalifan/51_Sarchia_Khalifan*.lstmf' > data/all-51_Sarchia_Khalifan-ckb-lstmf
find . -wholename './gt/ckb/52_Sarchia_Khursheed/52_Sarchia_Khursheed*.lstmf' > data/all-52_Sarchia_Khursheed-ckb-lstmf
find . -wholename './gt/ckb/53_Sarchia_Khwendnga/53_Sarchia_Khwendnga*.lstmf' > data/all-53_Sarchia_Khwendnga-ckb-lstmf
find . -wholename './gt/ckb/54_Sarchia_Kirkuk/54_Sarchia_Kirkuk*.lstmf' > data/all-54_Sarchia_Kirkuk-ckb-lstmf
find . -wholename './gt/ckb/55_Sarchia_Kurdish/55_Sarchia_Kurdish*.lstmf' > data/all-55_Sarchia_Kurdish-ckb-lstmf
find . -wholename './gt/ckb/57_Sarchia_Kurdistan/57_Sarchia_Kurdistan*.lstmf' > data/all-57_Sarchia_Kurdistan-ckb-lstmf
find . -wholename './gt/ckb/58_Sarchia_Lina/58_Sarchia_Lina*.lstmf' > data/all-58_Sarchia_Lina-ckb-lstmf
find . -wholename './gt/ckb/59_Sarchia_Lumia/59_Sarchia_Lumia*.lstmf' > data/all-59_Sarchia_Lumia-ckb-lstmf
find . -wholename './gt/ckb/60_Sarchia_Makka/60_Sarchia_Makka*.lstmf' > data/all-60_Sarchia_Makka-ckb-lstmf
