find . -wholename './gt/ckb-200/Microsoft_Uighur/Microsoft_Uighur*.lstmf' > data/all-Microsoft_Uighur-ckb-200-lstmf
find . -wholename './gt/ckb-200/Noto_Kufi_Arabic/Noto_Kufi_Arabic*.lstmf' > data/all-Noto_Kufi_Arabic-ckb-200-lstmf
find . -wholename './gt/ckb-200/Noto_Naskh_Arabic/Noto_Naskh_Arabic*.lstmf' > data/all-Noto_Naskh_Arabic-ckb-200-lstmf
find . -wholename './gt/ckb-200/Sakkal_Majalla/Sakkal_Majalla*.lstmf' > data/all-Sakkal_Majalla-ckb-200-lstmf
find . -wholename './gt/ckb-200/Scheherazade/Scheherazade*.lstmf' > data/all-Scheherazade-ckb-200-lstmf
find . -wholename './gt/ckb-200/Segoe_UI/Segoe_UI*.lstmf' > data/all-Segoe_UI-ckb-200-lstmf
find . -wholename './gt/ckb-200/Simplified_Arabic/Simplified_Arabic*.lstmf' > data/all-Simplified_Arabic-ckb-200-lstmf
find . -wholename './gt/ckb-200/Tahoma/Tahoma*.lstmf' > data/all-Tahoma-ckb-200-lstmf
find . -wholename './gt/ckb-200/Times_New_Roman/Times_New_Roman*.lstmf' > data/all-Times_New_Roman-ckb-200-lstmf
find . -wholename './gt/ckb-200/Traditional_Arabic/Traditional_Arabic*.lstmf' > data/all-Traditional_Arabic-ckb-200-lstmf
find . -wholename './gt/ckb-200/Vazir/Vazir*.lstmf' > data/all-Vazir-ckb-200-lstmf

find . -wholename './gt/ckb/Microsoft_Uighur/Microsoft_Uighur*.lstmf' > data/all-Microsoft_Uighur-ckb-lstmf
find . -wholename './gt/ckb/Noto_Kufi_Arabic/Noto_Kufi_Arabic*.lstmf' > data/all-Noto_Kufi_Arabic-ckb-lstmf
find . -wholename './gt/ckb/Noto_Naskh_Arabic/Noto_Naskh_Arabic*.lstmf' > data/all-Noto_Naskh_Arabic-ckb-lstmf
find . -wholename './gt/ckb/Sakkal_Majalla/Sakkal_Majalla*.lstmf' > data/all-Sakkal_Majalla-ckb-lstmf
find . -wholename './gt/ckb/Scheherazade/Scheherazade*.lstmf' > data/all-Scheherazade-ckb-lstmf
find . -wholename './gt/ckb/Segoe_UI/Segoe_UI*.lstmf' > data/all-Segoe_UI-ckb-lstmf
find . -wholename './gt/ckb/Simplified_Arabic/Simplified_Arabic*.lstmf' > data/all-Simplified_Arabic-ckb-lstmf
find . -wholename './gt/ckb/Tahoma/Tahoma*.lstmf' > data/all-Tahoma-ckb-lstmf
find . -wholename './gt/ckb/Times_New_Roman/Times_New_Roman*.lstmf' > data/all-Times_New_Roman-ckb-lstmf
find . -wholename './gt/ckb/Traditional_Arabic/Traditional_Arabic*.lstmf' > data/all-Traditional_Arabic-ckb-lstmf
find . -wholename './gt/ckb/Vazir/Vazir*.lstmf' > data/all-Vazir-ckb-lstmf