find . -wholename './gt/ckb-200/74_Sarchia_Qatar/74_Sarchia_Qatar*.lstmf' > data/all-74_Sarchia_Qatar-ckb-200-lstmf
find . -wholename './gt/ckb-200/75_Sarchia_Qutabkhana/75_Sarchia_Qutabkhana*.lstmf' > data/all-75_Sarchia_Qutabkhana-ckb-200-lstmf
find . -wholename './gt/ckb-200/76_Sarchia_Rojhalat/76_Sarchia_Rojhalat*.lstmf' > data/all-76_Sarchia_Rojhalat-ckb-200-lstmf
find . -wholename './gt/ckb-200/77_Sarchia_Rojnama_1/77_Sarchia_Rojnama_1*.lstmf' > data/all-77_Sarchia_Rojnama_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/79_Sarchia_Rwandiz/79_Sarchia_Rwandiz*.lstmf' > data/all-79_Sarchia_Rwandiz-ckb-200-lstmf
find . -wholename './gt/ckb-200/80_Sarchia_Salahaddin/80_Sarchia_Salahaddin*.lstmf' > data/all-80_Sarchia_Salahaddin-ckb-200-lstmf
find . -wholename './gt/ckb-200/81_Sarchia_Shano/81_Sarchia_Shano*.lstmf' > data/all-81_Sarchia_Shano-ckb-200-lstmf
find . -wholename './gt/ckb-200/82_Sarchia_Smart_1/82_Sarchia_Smart_1*.lstmf' > data/all-82_Sarchia_Smart_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/84_Sarchia_Smora/84_Sarchia_Smora*.lstmf' > data/all-84_Sarchia_Smora-ckb-200-lstmf
find . -wholename './gt/ckb-200/85_Sarchia_Soran/85_Sarchia_Soran*.lstmf' > data/all-85_Sarchia_Soran-ckb-200-lstmf
find . -wholename './gt/ckb-200/86_Sarchia_Speelk_1/86_Sarchia_Speelk_1*.lstmf' > data/all-86_Sarchia_Speelk_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/88_Sarchia_Sulaimani/88_Sarchia_Sulaimani*.lstmf' > data/all-88_Sarchia_Sulaimani-ckb-200-lstmf
find . -wholename './gt/ckb-200/89_Sarchia_Surchi/89_Sarchia_Surchi*.lstmf' > data/all-89_Sarchia_Surchi-ckb-200-lstmf

find . -wholename './gt/ckb/74_Sarchia_Qatar/74_Sarchia_Qatar*.lstmf' > data/all-74_Sarchia_Qatar-ckb-lstmf
find . -wholename './gt/ckb/75_Sarchia_Qutabkhana/75_Sarchia_Qutabkhana*.lstmf' > data/all-75_Sarchia_Qutabkhana-ckb-lstmf
find . -wholename './gt/ckb/76_Sarchia_Rojhalat/76_Sarchia_Rojhalat*.lstmf' > data/all-76_Sarchia_Rojhalat-ckb-lstmf
find . -wholename './gt/ckb/77_Sarchia_Rojnama_1/77_Sarchia_Rojnama_1*.lstmf' > data/all-77_Sarchia_Rojnama_1-ckb-lstmf
find . -wholename './gt/ckb/79_Sarchia_Rwandiz/79_Sarchia_Rwandiz*.lstmf' > data/all-79_Sarchia_Rwandiz-ckb-lstmf
find . -wholename './gt/ckb/80_Sarchia_Salahaddin/80_Sarchia_Salahaddin*.lstmf' > data/all-80_Sarchia_Salahaddin-ckb-lstmf
find . -wholename './gt/ckb/81_Sarchia_Shano/81_Sarchia_Shano*.lstmf' > data/all-81_Sarchia_Shano-ckb-lstmf
find . -wholename './gt/ckb/82_Sarchia_Smart_1/82_Sarchia_Smart_1*.lstmf' > data/all-82_Sarchia_Smart_1-ckb-lstmf
find . -wholename './gt/ckb/84_Sarchia_Smora/84_Sarchia_Smora*.lstmf' > data/all-84_Sarchia_Smora-ckb-lstmf
find . -wholename './gt/ckb/85_Sarchia_Soran/85_Sarchia_Soran*.lstmf' > data/all-85_Sarchia_Soran-ckb-lstmf
find . -wholename './gt/ckb/86_Sarchia_Speelk_1/86_Sarchia_Speelk_1*.lstmf' > data/all-86_Sarchia_Speelk_1-ckb-lstmf
find . -wholename './gt/ckb/88_Sarchia_Sulaimani/88_Sarchia_Sulaimani*.lstmf' > data/all-88_Sarchia_Sulaimani-ckb-lstmf
find . -wholename './gt/ckb/89_Sarchia_Surchi/89_Sarchia_Surchi*.lstmf' > data/all-89_Sarchia_Surchi-ckb-lstmf
