find . -wholename './gt/ckb-200/16_Sarchia_Bahasht_1/16_Sarchia_Bahasht_1*.lstmf' > data/all-16_Sarchia_Bahasht_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/18_Sarchia_Bakwr/18_Sarchia_Bakwr*.lstmf' > data/all-18_Sarchia_Bakwr-ckb-200-lstmf
find . -wholename './gt/ckb-200/19_Sarchia_Bananok/19_Sarchia_Bananok*.lstmf' > data/all-19_Sarchia_Bananok-ckb-200-lstmf
find . -wholename './gt/ckb-200/20_Sarchia_Banoka_1/20_Sarchia_Banoka_1*.lstmf' > data/all-20_Sarchia_Banoka_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/22_Sarchia_Baran/22_Sarchia_Baran*.lstmf' > data/all-22_Sarchia_Baran-ckb-200-lstmf
find . -wholename './gt/ckb-200/23_Sarchia_Barham/23_Sarchia_Barham*.lstmf' > data/all-23_Sarchia_Barham-ckb-200-lstmf
find . -wholename './gt/ckb-200/24_Sarchia_Bayan/24_Sarchia_Bayan*.lstmf' > data/all-24_Sarchia_Bayan-ckb-200-lstmf
find . -wholename './gt/ckb-200/25_Sarchia_Bilal/25_Sarchia_Bilal*.lstmf' > data/all-25_Sarchia_Bilal-ckb-200-lstmf
find . -wholename './gt/ckb-200/26_Sarchia_Blawkrawa_1/26_Sarchia_Blawkrawa_1*.lstmf' > data/all-26_Sarchia_Blawkrawa_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/28_Sarchia_Bokan/28_Sarchia_Bokan*.lstmf' > data/all-28_Sarchia_Bokan-ckb-200-lstmf
find . -wholename './gt/ckb-200/29_Sarchia_Chiaiy/29_Sarchia_Chiaiy*.lstmf' > data/all-29_Sarchia_Chiaiy-ckb-200-lstmf
find . -wholename './gt/ckb-200/30_Sarchia_Dashti/30_Sarchia_Dashti*.lstmf' > data/all-30_Sarchia_Dashti-ckb-200-lstmf
find . -wholename './gt/ckb-200/33_Sarchia_Dihok/33_Sarchia_Dihok*.lstmf' > data/all-33_Sarchia_Dihok-ckb-200-lstmf

find . -wholename './gt/ckb/16_Sarchia_Bahasht_1/16_Sarchia_Bahasht_1*.lstmf' > data/all-16_Sarchia_Bahasht_1-ckb-lstmf
find . -wholename './gt/ckb/18_Sarchia_Bakwr/18_Sarchia_Bakwr*.lstmf' > data/all-18_Sarchia_Bakwr-ckb-lstmf
find . -wholename './gt/ckb/19_Sarchia_Bananok/19_Sarchia_Bananok*.lstmf' > data/all-19_Sarchia_Bananok-ckb-lstmf
find . -wholename './gt/ckb/20_Sarchia_Banoka_1/20_Sarchia_Banoka_1*.lstmf' > data/all-20_Sarchia_Banoka_1-ckb-lstmf
find . -wholename './gt/ckb/22_Sarchia_Baran/22_Sarchia_Baran*.lstmf' > data/all-22_Sarchia_Baran-ckb-lstmf
find . -wholename './gt/ckb/23_Sarchia_Barham/23_Sarchia_Barham*.lstmf' > data/all-23_Sarchia_Barham-ckb-lstmf
find . -wholename './gt/ckb/24_Sarchia_Bayan/24_Sarchia_Bayan*.lstmf' > data/all-24_Sarchia_Bayan-ckb-lstmf
find . -wholename './gt/ckb/25_Sarchia_Bilal/25_Sarchia_Bilal*.lstmf' > data/all-25_Sarchia_Bilal-ckb-lstmf
find . -wholename './gt/ckb/26_Sarchia_Blawkrawa_1/26_Sarchia_Blawkrawa_1*.lstmf' > data/all-26_Sarchia_Blawkrawa_1-ckb-lstmf
find . -wholename './gt/ckb/28_Sarchia_Bokan/28_Sarchia_Bokan*.lstmf' > data/all-28_Sarchia_Bokan-ckb-lstmf
find . -wholename './gt/ckb/29_Sarchia_Chiaiy/29_Sarchia_Chiaiy*.lstmf' > data/all-29_Sarchia_Chiaiy-ckb-lstmf
find . -wholename './gt/ckb/30_Sarchia_Dashti/30_Sarchia_Dashti*.lstmf' > data/all-30_Sarchia_Dashti-ckb-lstmf
find . -wholename './gt/ckb/33_Sarchia_Dihok/33_Sarchia_Dihok*.lstmf' > data/all-33_Sarchia_Dihok-ckb-lstmf
