find . -wholename './gt/ckb-200/34_Sarchia_Erbil/34_Sarchia_Erbil*.lstmf' > data/all-34_Sarchia_Erbil-ckb-200-lstmf
find . -wholename './gt/ckb-200/35_Sarchia_Farsi/35_Sarchia_Farsi*.lstmf' > data/all-35_Sarchia_Farsi-ckb-200-lstmf
find . -wholename './gt/ckb-200/36_Sarchia_Fwad/36_Sarchia_Fwad*.lstmf' > data/all-36_Sarchia_Fwad-ckb-200-lstmf
find . -wholename './gt/ckb-200/37_Sarchia_Gul/37_Sarchia_Gul*.lstmf' > data/all-37_Sarchia_Gul-ckb-200-lstmf
find . -wholename './gt/ckb-200/38_Sarchia_Halab/38_Sarchia_Halab*.lstmf' > data/all-38_Sarchia_Halab-ckb-200-lstmf
find . -wholename './gt/ckb-200/39_Sarchia_Halabja/39_Sarchia_Halabja*.lstmf' > data/all-39_Sarchia_Halabja-ckb-200-lstmf
find . -wholename './gt/ckb-200/40_Sarchia_Hang/40_Sarchia_Hang*.lstmf' > data/all-40_Sarchia_Hang-ckb-200-lstmf
find . -wholename './gt/ckb-200/41_Sarchia_Harir/41_Sarchia_Harir*.lstmf' > data/all-41_Sarchia_Harir-ckb-200-lstmf
find . -wholename './gt/ckb-200/42_Sarchia_Hawin/42_Sarchia_Hawin*.lstmf' > data/all-42_Sarchia_Hawin-ckb-200-lstmf
find . -wholename './gt/ckb-200/43_Sarchia_Hawre/43_Sarchia_Hawre*.lstmf' > data/all-43_Sarchia_Hawre-ckb-200-lstmf
find . -wholename './gt/ckb-200/44_Sarchia_Honrawa/44_Sarchia_Honrawa*.lstmf' > data/all-44_Sarchia_Honrawa-ckb-200-lstmf
find . -wholename './gt/ckb-200/45_Sarchia_Iraq/45_Sarchia_Iraq*.lstmf' > data/all-45_Sarchia_Iraq-ckb-200-lstmf
find . -wholename './gt/ckb-200/46_Sarchia_Islam/46_Sarchia_Islam*.lstmf' > data/all-46_Sarchia_Islam-ckb-200-lstmf

find . -wholename './gt/ckb/34_Sarchia_Erbil/34_Sarchia_Erbil*.lstmf' > data/all-34_Sarchia_Erbil-ckb-lstmf
find . -wholename './gt/ckb/35_Sarchia_Farsi/35_Sarchia_Farsi*.lstmf' > data/all-35_Sarchia_Farsi-ckb-lstmf
find . -wholename './gt/ckb/36_Sarchia_Fwad/36_Sarchia_Fwad*.lstmf' > data/all-36_Sarchia_Fwad-ckb-lstmf
find . -wholename './gt/ckb/37_Sarchia_Gul/37_Sarchia_Gul*.lstmf' > data/all-37_Sarchia_Gul-ckb-lstmf
find . -wholename './gt/ckb/38_Sarchia_Halab/38_Sarchia_Halab*.lstmf' > data/all-38_Sarchia_Halab-ckb-lstmf
find . -wholename './gt/ckb/39_Sarchia_Halabja/39_Sarchia_Halabja*.lstmf' > data/all-39_Sarchia_Halabja-ckb-lstmf
find . -wholename './gt/ckb/40_Sarchia_Hang/40_Sarchia_Hang*.lstmf' > data/all-40_Sarchia_Hang-ckb-lstmf
find . -wholename './gt/ckb/41_Sarchia_Harir/41_Sarchia_Harir*.lstmf' > data/all-41_Sarchia_Harir-ckb-lstmf
find . -wholename './gt/ckb/42_Sarchia_Hawin/42_Sarchia_Hawin*.lstmf' > data/all-42_Sarchia_Hawin-ckb-lstmf
find . -wholename './gt/ckb/43_Sarchia_Hawre/43_Sarchia_Hawre*.lstmf' > data/all-43_Sarchia_Hawre-ckb-lstmf
find . -wholename './gt/ckb/44_Sarchia_Honrawa/44_Sarchia_Honrawa*.lstmf' > data/all-44_Sarchia_Honrawa-ckb-lstmf
find . -wholename './gt/ckb/45_Sarchia_Iraq/45_Sarchia_Iraq*.lstmf' > data/all-45_Sarchia_Iraq-ckb-lstmf
find . -wholename './gt/ckb/46_Sarchia_Islam/46_Sarchia_Islam*.lstmf' > data/all-46_Sarchia_Islam-ckb-lstmf
