find . -wholename './gt/ckb-200/90_Sarchia_Tablo/90_Sarchia_Tablo*.lstmf' > data/all-90_Sarchia_Tablo-ckb-200-lstmf
find . -wholename './gt/ckb-200/91_Sarchia_Taran_1/91_Sarchia_Taran_1*.lstmf' > data/all-91_Sarchia_Taran_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/93_Sarchia_TV/93_Sarchia_TV*.lstmf' > data/all-93_Sarchia_TV-ckb-200-lstmf
find . -wholename './gt/ckb-200/94_Sarchia_Yaran/94_Sarchia_Yaran*.lstmf' > data/all-94_Sarchia_Yaran-ckb-200-lstmf
find . -wholename './gt/ckb-200/95_Sarchia_Zain_1/95_Sarchia_Zain_1*.lstmf' > data/all-95_Sarchia_Zain_1-ckb-200-lstmf
find . -wholename './gt/ckb-200/97_Sarchia_Zer/97_Sarchia_Zer*.lstmf' > data/all-97_Sarchia_Zer-ckb-200-lstmf
find . -wholename './gt/ckb-200/98_Sarchia_ZherNus/98_Sarchia_ZherNus*.lstmf' > data/all-98_Sarchia_ZherNus-ckb-200-lstmf
find . -wholename './gt/ckb-200/99_Sarchia_Zhinga/99_Sarchia_Zhinga*.lstmf' > data/all-99_Sarchia_Zhinga-ckb-200-lstmf
find . -wholename './gt/ckb-200/Amiri/Amiri*.lstmf' > data/all-Amiri-ckb-200-lstmf
find . -wholename './gt/ckb-200/Amiri_Quran/Amiri_Quran*.lstmf' > data/all-Amiri_Quran-ckb-200-lstmf
find . -wholename './gt/ckb-200/KacstBook_Medium/KacstBook_Medium*.lstmf' > data/all-KacstBook_Medium-ckb-200-lstmf

find . -wholename './gt/ckb/90_Sarchia_Tablo/90_Sarchia_Tablo*.lstmf' > data/all-90_Sarchia_Tablo-ckb-lstmf
find . -wholename './gt/ckb/91_Sarchia_Taran_1/91_Sarchia_Taran_1*.lstmf' > data/all-91_Sarchia_Taran_1-ckb-lstmf
find . -wholename './gt/ckb/93_Sarchia_TV/93_Sarchia_TV*.lstmf' > data/all-93_Sarchia_TV-ckb-lstmf
find . -wholename './gt/ckb/94_Sarchia_Yaran/94_Sarchia_Yaran*.lstmf' > data/all-94_Sarchia_Yaran-ckb-lstmf
find . -wholename './gt/ckb/95_Sarchia_Zain_1/95_Sarchia_Zain_1*.lstmf' > data/all-95_Sarchia_Zain_1-ckb-lstmf
find . -wholename './gt/ckb/97_Sarchia_Zer/97_Sarchia_Zer*.lstmf' > data/all-97_Sarchia_Zer-ckb-lstmf
find . -wholename './gt/ckb/98_Sarchia_ZherNus/98_Sarchia_ZherNus*.lstmf' > data/all-98_Sarchia_ZherNus-ckb-lstmf
find . -wholename './gt/ckb/99_Sarchia_Zhinga/99_Sarchia_Zhinga*.lstmf' > data/all-99_Sarchia_Zhinga-ckb-lstmf
find . -wholename './gt/ckb/Amiri/Amiri*.lstmf' > data/all-Amiri-ckb-lstmf
find . -wholename './gt/ckb/Amiri_Quran/Amiri_Quran*.lstmf' > data/all-Amiri_Quran-ckb-lstmf
find . -wholename './gt/ckb/KacstBook_Medium/KacstBook_Medium*.lstmf' > data/all-KacstBook_Medium-ckb-lstmf
